### ISSUE TITLE
Almost There

### ISSUE THREAD

**Issue by Imaginativeone** [kaizenberg/UdelerX#11]
Downloaded to 97%, then went to 0 kb/s

**Comment by tiagobalsas** [comment]
Olá, a aplicação não tem mais suporte?

**Comment by qualita-apps** [comment]
This project is currently maintained by @heliomarpm

**Comment by qualita-apps** [comment]
> Olá, a aplicação não tem mais suporte?

This project is currently maintained by https://github.com/heliomarpm/udemy-downloader-gui
